fix(ide-extension): crash without git origin
inlang/inlang pull request #1024
Opened 2023-07-02 07:40 UTC by openscript

Uses `groupKey` "without-git", when there is no git origin

2023-07-02 12:42 UTC, samuelstroschein requested changes
Seems like you went the complicated route which would lead to bad telemetry data. 

### Request 

Simply don't perform a group identify if the origin is undefined, and don't use a stub ("without-git").

2023-07-02 12:42 UTC, samuelstroschein commented on source-code/ide-extension/src/services/telemetry/implementation.ts
> +		return 'without-git'
return `undefined`

2023-07-02 12:42 UTC, samuelstroschein commented on source-code/ide-extension/src/main.ts
> +		})
don't group identify if the origin is `undefined`. 

```ts

if (gitOrigin) {
telemetry.groupIdentify({
			groupType: "repository",
			groupKey: gitOrigin,
			properties: {
				name: gitOrigin,
			},
		})
}

2023-07-02 12:42 UTC, samuelstroschein commented on source-code/ide-extension/src/services/telemetry/implementation.ts
> +		console.warn(e)
I would remove the console.warn. There is nothing "bad" going on if a directory has not git repo.

2023-07-03 08:47 UTC, felixhaeberle approved these changes
lgtm 👍

2023-07-03 08:48 UTC, merged