feat: edit on GH button
inlang/inlang pull request #1165
Opened 2023-07-24 09:00 UTC by floriandwt

added:
- button to edit directly a docs page on GitHub

Have changed the table of contents because of that.
Based on https://github.com/inlang/internal/issues/127

2023-07-24 15:28 UTC, samuelstroschein commented
@floriandwt who should review this?

2023-07-24 15:34 UTC, floriandwt commented
Based on https://github.com/inlang/internal/issues/127

2023-07-24 15:37 UTC, floriandwt commented
@NilsJacobsen you mind quickly looking into it? It's basically just the edit button and the client side documentation file + the tableOfContents (tableOfContents is now dynamically generated based on an object above called fileSources, to filter out the original fileSources for the edit button) that was edited.

2023-07-25 08:57 UTC, NilsJacobsen commented on source-code/website/src/pages/documentation/EditButton.tsx
> +				Edit on GitHub
What about adding an icon as a prefix? I think that makes in more clearly clickable. And directly implies what it is. 
https://icon-sets.iconify.design/material-symbols/edit-outline-rounded/ maybe this one. U should be able to import the material symbols like the other icons.

2023-07-25 09:02 UTC, NilsJacobsen commented on source-code/website/src/pages/documentation/index.page.tsx
> +							const fileSource = fileSources[section][index]
I get an typeerror here, can you resolve it?

2023-07-25 09:04 UTC, NilsJacobsen requested changes
See comments

2023-07-26 07:20 UTC, NilsJacobsen approved these changes
That looks great. Affordance of button is great with the pen. Good job.

2023-07-26 07:20 UTC, NilsJacobsen reviewed
Let me check if I can get rid of the lint error

2023-07-26 07:44 UTC, NilsJacobsen commented
https://github.com/inlang/inlang/issues/1090#issuecomment-1651150433

Let's merge this shouldn't affect this merge.

2023-07-26 08:18 UTC, merged