chore(ide-extension): upgrade project setup
inlang/inlang pull request #347
Opened 2023-02-03 10:16 UTC by openscript

- Adds a dev container configuration
- Updates contributing.md according to the dev container configuration
- Updates dependencies
- Enhances project configuration
- Enhances launch scripts
- Removes Rollup (VSCode extension template removed it too. An option is to use webpack, but it makes the project setup complicated and I don't think inlang needs it)

2023-02-05 23:00 UTC, samuelstroschein requested changes
I propose to not merge this PR due to: 

a) The PR introduces changes that are unrelated to the container setup (and might be reverted by the follow up PR).
b) The container setup does not work for the codebase except for the ide extension.
c) Merging this PR will likely lead to merge conflicts. Numerous changes are required that will lead to merge conflicts with the follow-up PR that re-introduces the IDE extension. I propose waiting for the other PR first. 

Regarding b), the container setup only works for the ide extension. Turborepo, and therefore the entire code base, fails to run. I suspect the "node-typescript" dev container is to blame because it only includes "node"? 

I take that https://github.com/inlang/inlang/issues/312 is a larger undertaking but dev containers seem to be the way to go and I should set them up!

If you agree with closing this PR, wait for the follow-up PR, and then tackle the dev setup, close this PR. Otherwise, let me know how to continue

2023-02-06 05:23 UTC, openscript commented on source-code/ide-extension/rollup.config.js
> -
I don't completely understand if VSCode extensions really need to be CJS modules.

At the other hand officially VS Code doesn't use Rollup anymore. They removed it from their templates and tutorials.

What I try here is to stick to their proposed set up.

2023-02-06 05:25 UTC, openscript commented on source-code/ide-extension/src/test/suite/index.ts
> +        mocha.run(failures => {
Yes, I think this is possible.

2023-02-06 05:26 UTC, openscript commented on source-code/ide-extension/tsconfig.json
> -    "module": "Node16",
Yes, I agree.

2023-02-06 05:26 UTC, openscript commented on source-code/ide-extension/package.json
> +    "compile": "tsc -p ./",
Yes, I agree.

2023-02-06 05:27 UTC, openscript commented on CONTRIBUTING.md
> -4. Open "localhost:xxxx" in the browser that has been opened.
I'll add another paragraph for this and mention the launch configuration.

2023-02-06 05:29 UTC, openscript commented
I could use turbo and successfully build the entire project. What errors you get?

2023-02-06 10:33 UTC, samuelstroschein commented
> sh: 1: turbo: Exec format error

2023-02-06 10:35 UTC, samuelstroschein commented on source-code/ide-extension/rollup.config.js
> -
If it works great, one dependency less. Electron does not support ESM though. I suspect the official template to use CJS.

https://github.com/microsoft/vscode/issues/130367
https://github.com/standard-things/esm/issues/915

2023-02-06 10:52 UTC, openscript commented
No problem for me if you open another one and I'm also happy to contribute there.

2023-02-06 21:18 UTC, samuelstroschein commented
Closed by #363.

2023-02-06 21:18 UTC, closed without merging